### ISSUE TITLE
Regarding the training file of the model

### ISSUE THREAD

**Issue by AbhishekMankame** [pallavi-2/Hackathon#1]
I came across this GitHub repository and I noticed that there is a missing code that I need to run my project. I am reaching out to ask if it is possible for you to share the training file. I would greatly appreciate it if you could share this file with me so that I can move forward with my work.

Thank you for your time and consideration.

**Comment by pallavi-2** [comment]
I am sorry but I was not the one who trained the model. I was only responsible for creating the API.

**Comment by AbhishekMankame** [comment]
Ok, thanks for the information
